import { useEffect, useRef } from 'react';
import type { Station } from '@/lib/skyguard-api';
declare global { interface Window { L?: any } }
const COLORS={Normal:'#22c55e',Warning:'#f59e0b',Critical:'#ef4444'};
export function NetworkMap({stations,selected,onSelect}:{stations:Station[];selected:string;onSelect:(id:string)=>void}){
 const ref=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{let map:any;let timer:any;const init=()=>{if(!ref.current||!window.L)return;map=window.L.map(ref.current,{zoomControl:true,scrollWheelZoom:true,attributionControl:true});window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const markers:any[]=[];stations.forEach(s=>{const c=COLORS[s.status as keyof typeof COLORS]||COLORS.Normal;const marker=window.L.circleMarker([s.latitude,s.longitude],{radius:selected===s.station_id?10:7,color:c,fillColor:c,fillOpacity:.9,weight:selected===s.station_id?3:2}).addTo(map);marker.bindPopup(`<b>${s.name}</b><br/>ID: ${s.station_id}<br/>Health: ${s.health.toFixed(0)}%<br/>Status: ${s.status}<br/>${s.latitude.toFixed(4)}, ${s.longitude.toFixed(4)}`);marker.on('click',()=>onSelect(s.station_id));markers.push(marker)});if(stations.length===1)map.setView([stations[0].latitude,stations[0].longitude],9);else if(stations.length)map.fitBounds(window.L.latLngBounds(stations.map(s=>[s.latitude,s.longitude])),{padding:[30,30],maxZoom:8});else map.setView([11.1271,78.6569],7);return()=>markers.forEach(m=>m.remove())};if(window.L)init();else timer=setInterval(()=>{if(window.L){clearInterval(timer);init()}},100);return()=>{clearInterval(timer);if(map)map.remove()};},[stations,selected,onSelect]);
 return <div className="relative h-full min-h-64 w-full flex-1 overflow-hidden rounded-md border border-border bg-card"><div ref={ref} className="absolute inset-0"/><div className="absolute bottom-2 left-2 z-[1000] flex gap-3 rounded-md bg-background/90 px-2 py-1 text-[0.6rem] text-muted-foreground backdrop-blur">{Object.keys(COLORS).map(k=><span key={k} className="flex items-center gap-1"><i className="size-1.5 rounded-full" style={{backgroundColor:COLORS[k as keyof typeof COLORS]}}/>{k}</span>)}</div></div>
}
