from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def build_readings_pdf(rows, station_id=None):
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), rightMargin=10*mm, leftMargin=10*mm, topMargin=10*mm, bottomMargin=10*mm)
    styles = getSampleStyleSheet()
    story = [Paragraph('SkyGuard AI — AWS Anomaly Report', styles['Title']),
             Paragraph(f'Station: {station_id or "All stations"}', styles['Normal']), Spacer(1, 5*mm)]
    data = [['Timestamp','Station','Temp °C','Pressure hPa','Humidity %','Anomaly','Score','Confidence','Severity','Root Cause']]
    for r in rows:
        data.append([str(r.timestamp), r.station_id, f'{r.temperature:.1f}', f'{r.pressure:.1f}', f'{r.humidity:.1f}',
                     'YES' if r.anomaly else 'NO', f'{r.score:.2f}', f'{r.confidence:.2f}', r.severity, r.root_cause])
    table = Table(data, repeatRows=1, colWidths=[34*mm, 30*mm, 18*mm, 23*mm, 21*mm, 18*mm, 15*mm, 21*mm, 20*mm, 58*mm])
    table.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),colors.HexColor('#1f2937')), ('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'), ('FONTSIZE',(0,0),(-1,-1),7),
        ('GRID',(0,0),(-1,-1),0.25,colors.HexColor('#cbd5e1')), ('VALIGN',(0,0),(-1,-1),'TOP'),
        ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white, colors.HexColor('#f8fafc')]),
    ]))
    story.append(table)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(f'Total records: {len(rows)} | Generated by SkyGuard AI', styles['Normal']))
    doc.build(story)
    buf.seek(0)
    return buf
